name: Cron Job

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Cache uv environment
        uses: actions/cache@v4
        with:
          path: |
            .venv
            .uv
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ${{ env.HOME }}/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            playwright-${{ runner.os }}-

      - name: Install dependencies
        run: uv sync

      - name: Install Playwright browsers
        run: uv run playwright install --with-deps

      - name: Debug Playwright cache
        run: ls -R $HOME/.cache/ms-playwright || echo "No cache found"

      - name: Run script
        env:
          INIT_URL: ${{ secrets.INIT_URL }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          CONFIG_JSON: ${{ vars.CONFIG_JSON }}
          TIMEDELTA_IN_DAYS: ${{ vars.TIMEDELTA_IN_DAYS }}
        run: uv run python main.py
